"""Stage 1 training entrypoints and shared helpers."""

from .runner import (
    CHECKPOINT_KIND_FULL,
    CHECKPOINT_KIND_MODEL_ONLY,
    append_token_to_model_inputs,
    build_processor_kwargs,
    build_prompt_text,
    compute_token_accuracy,
    first_record_from_dataset,
    format_gib,
    inject_history_inputs_embeds,
    load_checkpoint,
    log_gpu_preflight,
    main,
    maybe_wandb_finish,
    maybe_wandb_log,
    metric_improved,
    model_forward_inputs,
    move_inputs_to_device,
    prepare_batch,
    prepare_prompt_inputs_with_history,
    release_cuda_memory,
    set_seed,
    stage1_collate,
    write_run_config,
)

__all__ = [
    "CHECKPOINT_KIND_FULL",
    "CHECKPOINT_KIND_MODEL_ONLY",
    "append_token_to_model_inputs",
    "build_processor_kwargs",
    "build_prompt_text",
    "compute_token_accuracy",
    "first_record_from_dataset",
    "format_gib",
    "inject_history_inputs_embeds",
    "load_checkpoint",
    "log_gpu_preflight",
    "main",
    "maybe_wandb_finish",
    "maybe_wandb_log",
    "metric_improved",
    "model_forward_inputs",
    "move_inputs_to_device",
    "prepare_batch",
    "prepare_prompt_inputs_with_history",
    "release_cuda_memory",
    "set_seed",
    "stage1_collate",
    "write_run_config",
]
